# This file was generated by GoReleaser. DO NOT EDIT.
cask "logmind" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "7ab6dc2c2c4990475c2c2346042516606e43511b14afcd6d12673dc553741f1e"
      url "https://github.com/thrillmade/logmind/releases/download/v#{version}/logmind_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8271453a1fb0a3421e98a5371f6a250bd80e2c5a794c0494f2650b0b253a44ff"
      url "https://github.com/thrillmade/logmind/releases/download/v#{version}/logmind_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8be04e62c7f8d5f7919afac6f488ea08333e0556d347cf479cd596a5af314876"
      url "https://github.com/thrillmade/logmind/releases/download/v#{version}/logmind_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "455abf633b2275c0b6c212e4d9edc6de1ec6ffd691a779d74c500a7ddcea1ce8"
      url "https://github.com/thrillmade/logmind/releases/download/v#{version}/logmind_#{version}_linux_arm64.tar.gz"
    end
  end

  name "logmind"
  desc "Decision logging for AI-assisted development — branch-aware by default."
  homepage "https://logmind.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logmind"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/logmind"]
    end
  end

  # No zap stanza required

end
