# This file was generated by GoReleaser. DO NOT EDIT.
cask "logmind" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "634087e6a2aa24e47f91c223250d6aea650df3458dd81396be6bbed97d4ee594"
      url "https://github.com/thrillmade/logmind/releases/download/v#{version}/logmind_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1a3f25e78e6a264d695d86df5fc48f3d3961cdc0a3162da60038fdb0aa042a25"
      url "https://github.com/thrillmade/logmind/releases/download/v#{version}/logmind_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4b49ca6b7542ba26f7c590d08a3bb501c37b71013b07a17f8b7bb109a47bdcfd"
      url "https://github.com/thrillmade/logmind/releases/download/v#{version}/logmind_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2d847624e72063c7bb44d67cda53753ecb9c6bcd317b7ed2d0276e4753130120"
      url "https://github.com/thrillmade/logmind/releases/download/v#{version}/logmind_#{version}_linux_arm64.tar.gz"
    end
  end

  name "logmind"
  desc "Decision logging for AI-assisted development — branch-aware by default."
  homepage "https://logmind.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logmind"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/logmind"]
    end
  end

  # No zap stanza required

end
