# This file was generated by GoReleaser. DO NOT EDIT.
cask "logmind" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "a0175862232bddfaeab2a467ac0fcbeead1cecfc3a1e9f4f2e9111c915d36c07"
      url "https://github.com/thrillmade/logmind/releases/download/v#{version}/logmind_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "51082009c58fa7ce9b4fcbeee5ccc84d33d56f28ea6d81903df60aae51bdc2c9"
      url "https://github.com/thrillmade/logmind/releases/download/v#{version}/logmind_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "52e9e5e161ebd0b8366088556f5697a4ba7fb4660abe5c17ea8fc2ef7da8b6ad"
      url "https://github.com/thrillmade/logmind/releases/download/v#{version}/logmind_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0eff92c864118aa5f8bb0c266d541b7f8e2306e39095e60c6f37c1663cdc2679"
      url "https://github.com/thrillmade/logmind/releases/download/v#{version}/logmind_#{version}_linux_arm64.tar.gz"
    end
  end

  name "logmind"
  desc "Decision logging for AI-assisted development — branch-aware by default."
  homepage "https://logmind.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logmind"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/logmind"]
    end
  end

  # No zap stanza required

end
